version: "3.7"
services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    networks:
      - test

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - test

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - test

  db:
    image: library/mysql:5.7.30
    container_name: test-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - test

networks:
  test:
    driver: bridge

volumes:
  db-data: